spring.application.name=inventario

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=inventario_belleza;encrypt=false;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
springdoc.swagger-ui.path=/swagger-ui.html