# ?? Servidor ??????????????????????????????????????????????
server.port=80
server.servlet.context-path=/api

# ?? DataSource (SQL Server con usuario/contrasena) ????????
spring.datasource.url=jdbc:sqlserver://SERVIDOR-PROD:1433;databaseName=inventario_belleza;encrypt=true;integratedSecurity=false;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=SA
spring.datasource.password=TU_PASSWORD

# ?? JPA / Hibernate ???????????????????????????????????????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ?? Logging ???????????????????????????????????????????????
logging.level.root=ERROR